export type ResidenceServiceIconId =
  | 'luggage'
  | 'tv'
  | 'courtesy-kit'
  | 'ac'
  | 'wifi'
  | 'parking'
  | 'parking-paid'
  | 'extra-cleaning'
  | 'laundry'
  | 'transport'
  | 'tennis'
  | 'bike-rental'
  | 'boat-rental'
  | 'diving'
  | 'asinara'
  | 'guided-tours';
